version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: todo_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
