name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: todo_password
          POSTGRES_DB: todo_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U todo_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build 
      uses: docker/build-push-action@v6 
      with: 
        push: true
        tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/to-do:${{ github.sha}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "To-do"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_PROFILE }}
        images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/to-do:${{ github.sha}}:latest'